import { Injectable } from '@angular/core';
import {Observable, of} from 'rxjs';
import {Product} from '../../shared/product/product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  private products: Product[] = [
    {
      _id: 1,
      code: 1,
      name: 'aceite 20w50',
      brand: 'penzoil',
      manufacture: 'penzoil SA',
      quantity: '1000 ml',
      detail: 'para vehiculos livianos',
      package: 1000,
      presentation: 'ml',
      consumeUnit: 'l (litro)',
    },
    {
      _id: 2,
      code: 2,
      name: 'tubo pvc 1/2 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 100,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 3,
      code: 3,
      name: 'turboNico',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      quantity: '400 Kg',
      detail: 'alimento reforzador de aminoacidos',
      package: 400,
      presentation: 'kg',
      consumeUnit: 'libras',
    },
    {
      _id: 4,
      code: 4,
      name: 'tubo pvc 1 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 6,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 5,
      code: 5,
      name: 'tubo pvc 1 1/2plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 5,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 6,
      code: 6,
      name: 'tubo pvc 2 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 1,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 7,
      code: 7,
      name: 'Nico Smart',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 20,
      presentation: 'kg',
      quantity: '20 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 8,
      code: 8,
      name: 'Nico Bird',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 10,
      presentation: 'kg',
      quantity: '10 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 9,
      code: 9,
      name: 'Nico Prebord',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 5,
      presentation: 'kg',
      quantity: '5 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 10,
      code: 10,
      name: 'tubo pvc 1/2 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 100,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 11,
      code: 11,
      name: 'turboNico',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      quantity: '400 Kg',
      detail: 'alimento reforzador de aminoacidos',
      package: 400,
      presentation: 'kg',
      consumeUnit: 'libras',
    },
    {
      _id: 12,
      code: 12,
      name: 'tubo pvc 1 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 6,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 13,
      code: 13,
      name: 'tubo pvc 1 1/2plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 5,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 14,
      code: 14,
      name: 'tubo pvc 2 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 1,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 15,
      code: 15,
      name: 'Nico Smart',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 20,
      presentation: 'kg',
      quantity: '20 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 16,
      code: 16,
      name: 'Nico Bird',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 10,
      presentation: 'kg',
      quantity: '10 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 17,
      code: 17,
      name: 'Nico Prebord',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 5,
      presentation: 'kg',
      quantity: '5 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 18,
      code: 18,
      name: 'Nico Bird',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 10,
      presentation: 'kg',
      quantity: '10 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 19,
      code: 19,
      name: 'Nico Prebord',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 5,
      presentation: 'kg',
      quantity: '5 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 20,
      code: 20,
      name: 'tubo pvc 1/2 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 100,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 21,
      code: 21,
      name: 'aceite 20w50',
      brand: 'penzoil',
      manufacture: 'penzoil SA',
      quantity: '1000 ml',
      detail: 'para vehiculos livianos',
      package: 1000,
      presentation: 'ml',
      consumeUnit: 'l (litro)',
    },
    {
      _id: 22,
      code: 22,
      name: 'tubo pvc 1/2 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 100,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 23,
      code: 23,
      name: 'turboNico',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      quantity: '400 Kg',
      detail: 'alimento reforzador de aminoacidos',
      package: 400,
      presentation: 'kg',
      consumeUnit: 'libras',
    },
    {
      _id: 24,
      code: 24,
      name: 'tubo pvc 1 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 6,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 25,
      code: 25,
      name: 'tubo pvc 1 1/2plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 5,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 26,
      code: 26,
      name: 'tubo pvc 2 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 1,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 27,
      code: 27,
      name: 'Nico Smart',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 20,
      presentation: 'kg',
      quantity: '20 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 28,
      code: 28,
      name: 'Nico Bird',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 10,
      presentation: 'kg',
      quantity: '10 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 29,
      code: 29,
      name: 'Nico Prebord',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 5,
      presentation: 'kg',
      quantity: '5 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 30,
      code: 30,
      name: 'tubo pvc 1/2 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 100,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 31,
      code: 31,
      name: 'turboNico',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      quantity: '400 Kg',
      detail: 'alimento reforzador de aminoacidos',
      package: 400,
      presentation: 'kg',
      consumeUnit: 'libras',
    },
    {
      _id: 32,
      code: 32,
      name: 'tubo pvc 1 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 6,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 33,
      code: 33,
      name: 'tubo pvc 1 1/2plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 5,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 34,
      code: 34,
      name: 'tubo pvc 2 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 1,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    },
    {
      _id: 35,
      code: 35,
      name: 'Nico Smart',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 20,
      presentation: 'kg',
      quantity: '20 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 36,
      code: 36,
      name: 'Nico Bird',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 10,
      presentation: 'kg',
      quantity: '10 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 37,
      code: 37,
      name: 'Nico Prebord',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 5,
      presentation: 'kg',
      quantity: '5 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 38,
      code: 38,
      name: 'Nico Bird',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 10,
      presentation: 'kg',
      quantity: '10 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 39,
      code: 39,
      name: 'Nico Prebord',
      brand: 'Nicovita',
      manufacture: 'NicoPlant SA',
      detail: 'alimento reforzador de aminoacidos',
      package: 5,
      presentation: 'kg',
      quantity: '5 kg',
      consumeUnit: 'libras',
    },
    {
      _id: 40,
      code: 40,
      name: 'tubo pvc 1/2 plg',
      brand: 'tubos Ecuador',
      manufacture: 'TBECU SA',
      quantity: '1x3mts',
      detail: 'tubos para canalizacion electrica',
      package: 100,
      presentation: 'unidad',
      consumeUnit: 'unidad',
    }
    // {
    //   _id: 4,
    //   code: 4,
    //   name: '',
    //   brand: '',
    //   manufacture: '',
    //   quantity: '',
    //   detail: 'para vehiculos livianos';
    // },
    // {
    //   _id: 5,
    //   name: '',
    //   brand: '',
    //   manufacture: '',
    //   quantity: '',
    //   detail: 'para vehiculos livianos';
    // },
  ];
  constructor() { }
  public getProducts(): Observable<Product[]> {
      return of(this.products);
  }
  public getProduct(id: number): Observable<Product> {
      return of(this.products.filter(p => p._id === id)[0]);
  }
}
